config/routes.rb
Sisk::Application.routes.draw do

  resources :site_configs

  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }, :token_authentication_key => 'authentication_key'
  resources :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :custom_sites
  resources :sections
  resources :benefits
  resources :sites do
    member do
      get "usage", to: 'sites#usage'
      get "savings", to: 'sites#savings'
      get "about", to: 'sites#about'
      get "savings", to: 'sites#savings'
      get "health", to: 'sites#health'
      get "insurance", to: 'sites#insurance'
      get "security", to: 'sites#security'
      get "register", to: 'sites#register'
      post "pull_savings", to: 'sites#pull_savings'
      get "pull_print_coupon", to: 'sites#pull_print_coupon'
      get "login", to: 'sites#login'
    end
  end

  get "home/index"
  get "usage", :to => 'home#usage'
  get "privacy", :to => 'home#privacy'
  get "mb/:site_slug", :to => 'custom_sites#index', :as => 'custom_site_home'
  get "mb/:site_slug/about", :to => 'custom_sites#about', :as => 'custom_sites_about'
  get "mb/:site_slug/savings", :to => 'custom_sites#savings', :as => 'custom_sites_savings'
  get "mb/:site_slug/health", :to => 'custom_sites#health', :as => 'custom_sites_health'
  get "mb/:site_slug/insurance", :to => 'custom_sites#insurance', :as => 'custom_sites_insurance'
  get "mb/:site_slug/security", :to => 'custom_sites#security', :as => 'custom_sites_security'

  root :to => "home#index"
  get "about", to: 'home#about'

  # apipie
  namespace :api do
    namespace :v1 do
      resources :benefits do
        resources :sections
      end
      resources :site_configs
      devise_for :users, :controllers => { :sessions => "api/v1/sessions"}
    end
  end

end

app/views/shared/_footer.html.haml
%footer.main-footer
  .row.test.ft-widget-wrap
    %article#text-3.large-3.columns.widget.widget_text
      .textwidget
        = image_tag 'logo.png', class: 'mb10'
        %p
          \&#xA9;2014 Sisk. All Rights Reserved.
          %br/
          Site designed with love by
          %a{href: "http://www.theinfiniteagency.com"} Infinite
    %article#text-2.large-4.columns.widget.widget_text
      %h3.white Member Benefits
      .textwidget
        %p
          %strong provided by The Sisk Company
          %br
          4055 International Plaza
          %br/
          Suite 440
          %br/
          Fort Worth, TX 76109
    %article#text-4.large-3.columns.widget.widget_text
      .textwidget
        %p
          Toll Free: 1-800-899-7175
          %br/
          Local: 817-735-4884
          %br/
          = link_to "info@siskcompany.com", "mailto:info@siskcompany.com"
    %article#text-5.large-2.columns.widget.widget_text
      %h3.white Sitemap
      %ul.sitemap
        - if @site
          %li= link_to 'Home', @site
          %li= link_to 'About', about_site_path(@site)
          - if @site.savings_benefits.any?
            %li= link_to 'Savings', savings_site_path(@site)
          - if @site.health_benefits.any?
            %li= link_to 'Health', health_site_path(@site)
          - if @site.insurance_benefits.any?
            %li= link_to 'Insurance', insurance_site_path(@site)
          - if @site.security_benefits.any?
            %li= link_to 'Security', security_site_path(@site)
        - else
          %li= link_to 'Home', '/'
          %li= link_to 'About', '/about'
        %li= link_to "Privacy Policy", privacy_path
%a.exit-off-canvas

app/views/shared/_header.html.haml
%nav.tab-bar.show-for-medium-down
  %section.right-small
    %a.right-off-canvas-toggle.menu-icon
      %span
  %section.middle.tab-bar-section
    - if @site
      = link_to @site do
        = image_tag 'mobile-logo.png'
    - else
      %a{href: "/"}
        =image_tag 'mobile-logo.png'
%aside.right-off-canvas-menu
  %ul.off-canvas-list
    = render 'shared/mobile_navigation_links'

.header
  .top-bar-container.contain-to-grid.show-for-large-up
    %nav.top-bar{"data-topbar" => ""}
      .row
        .medium-2.columns.logo-wrap
          - if @site
            = link_to @site do
              = image_tag 'logo.png'
          - else
            %a{href: "/"}
              =image_tag 'logo.png'
        .medium-7.columns.left
          %ul#main-menu.top-bar-menu
            = render 'layouts/navigation_links'
        .medium-3.columns.right
          - if user_signed_in?
            = render 'shared/settings_nav'

app/views/shared/_home_hero.html.haml
- content_for :home_hero do
  %section.container{role: "document"}
    .row
      %section#home-hero
        .row
          .large-7.columns.right
            .fifty-percent.show-for-large-up
              %h2 Save Money, Great Value, Peace of Mind
            .show-for-medium-down.center
              %h2 Save Money, Great Value, Peace of Mind
          %aside.large-4.large-offset-1.home-login-form.left
            .inner
              %header Access Benefits
              #errorMSG
              = render 'shared/login_form'

app/views/shared/_login_form.html.haml
.login-form-wrap
  %h4.text-center.white.uppercase Access Benefits
  .row
    = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :remote => true, :format => :json, :html => {:class => 'form', :autocomplete => "off", :id => "new_login" }) do |f|
      = f.error_notification
      = devise_error_messages!
      = display_base_errors resource
      %ul#errors
      .large-3.medium-12.small-12.columns
        %label.left.inline.white.login-label{for: "user_email"} Email
      .large-9.medium-12.columns.small-12
        = f.input_field :email
      .clearfix
      .large-3.medium-12.columns.small-12
        %label.left.inline.white.login-label{for: "user_password"} Password
      .large-9.medium-12.columns.small-12
        = f.input_field :password
      .medium-12.columns
        .clearfix
        -# = f.check_box :remember_me, label: "Remember Me"
        = f.check_box :remember_me, class: "remember-box"
        = f.label :remember_me, class: "remember-label"
        .clearfix
        = f.submit "Send", class: "home-submit login-button radius"
        .clearfix
        = link_to 'Register for an account', new_user_registration_path, class: 'home-submit home-register login-button radius'
        .clearfix
        - if devise_mapping.recoverable? && controller_name != 'passwords'
          = link_to "Forgot your password?", new_password_path(resource_name), class: 'forgot-password'
        .clearfix
        %p
          %small.white *Membership features vary by account type and all of the features listed on this page may not be included with your package.  Please login to see the features included with your membership.

app/views/shared/_mobile_announcement.html.haml
.mobile-announcement-mobile.hide-for-large-up
  %a.droid-dl{href: "https://play.google.com/store/apps/details?id=air.sisk", target: "_blank"}
    = image_tag 'google-play-mobile.png'
  -# %a.apple-dl{href: "https://itunes.apple.com/us/app/member-benefits-sisk/id915619672?mt=8&uo=4", target: "_blank"}
  -#   = image_tag 'itunes-mobile.png'

app/views/shared/_mobile_navigation_links.html.haml
- if @site
  - if @site.savings_benefits.any?
    %li
      = link_to "Savings", savings_site_path(@site)
  - if @site.health_benefits.any?
    %li
      = link_to "Health", health_site_path(@site)
  - if @site.insurance_benefits.any?
    %li
      = link_to "Insurance", insurance_site_path(@site)
  - if @site.security_benefits.any?
    %li
      = link_to "Security", security_site_path(@site)
- else
  %li
    %a{href: "/about"} About Us
- if user_signed_in?
  %li= link_to "Account", edit_user_registration_path
  %li= link_to "Log Out", destroy_user_session_path, method: :delete
.clearfix

app/views/shared/_settings_nav.html.haml
.show-for-large-up
  = link_to "Account", edit_user_registration_path, class: 'account-button left'
  = link_to "Logout", destroy_user_session_path, method: :delete, class: 'account-button left'

app/views/shared/_site_header.html.haml
%nav.tab-bar.show-for-medium-down
  %section.right-small
    %a.right-off-canvas-toggle.menu-icon
      %span
  %section.middle.tab-bar-section
    - if @site
      = link_to @site do
        = image_tag 'mobile-logo.png'
    - else
      %a{href: "/"}
        =image_tag 'mobile-logo.png'
%aside.right-off-canvas-menu
  %ul.off-canvas-list
    = render 'shared/mobile_navigation_links'

.header
  .top-bar-container.contain-to-grid.show-for-large-up
    %nav.top-bar{"data-topbar" => ""}
      %ul.title-area
        %li.name
          %h1
            - if @site
              = link_to @site do
                = image_tag 'logo.png'
            - else
              %a{href: "/"}
                =image_tag 'logo.png'
      %section.top-bar-section
        %ul#main-menu.top-bar-menu.right
          = render 'layouts/navigation_links'

app/views/shared/_template_navigation_links.html.haml
%li.menu-item.hover-dim
  = link_to "Savings", custom_sites_savings_path(@custom_site.url)
%li.menu-item.hover-dim
  = link_to "Health", custom_sites_health_path(@custom_site.url)
%li.menu-item.hover-dim
  = link_to "Insurance", custom_sites_insurance_path(@custom_site.url)
%li.menu-item.hover-dim
  = link_to "Security", custom_sites_security_path(@custom_site.url)