config/routes.rb
Sisk::Application.routes.draw do

  resources :site_configs

  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" }, :token_authentication_key => 'authentication_key'
  resources :users

  devise_for :admin_users, ActiveAdmin::Devise.config
  resources :custom_sites
  resources :sections
  resources :benefits
  resources :sites do
    member do
      get "usage", to: 'sites#usage'
      get "savings", to: 'sites#savings'
      get "about", to: 'sites#about'
      get "savings", to: 'sites#savings'
      get "health", to: 'sites#health'
      get "insurance", to: 'sites#insurance'
      get "security", to: 'sites#security'
      get "register", to: 'sites#register'
      post "pull_savings", to: 'sites#pull_savings'
      get "pull_print_coupon", to: 'sites#pull_print_coupon'
      get "login", to: 'sites#login'
    end
  end

  get "home/index"
  get "usage", :to => 'home#usage'
  get "privacy", :to => 'home#privacy'
  get "mb/:site_slug", :to => 'custom_sites#index', :as => 'custom_site_home'
  get "mb/:site_slug/about", :to => 'custom_sites#about', :as => 'custom_sites_about'
  get "mb/:site_slug/savings", :to => 'custom_sites#savings', :as => 'custom_sites_savings'
  get "mb/:site_slug/health", :to => 'custom_sites#health', :as => 'custom_sites_health'
  get "mb/:site_slug/insurance", :to => 'custom_sites#insurance', :as => 'custom_sites_insurance'
  get "mb/:site_slug/security", :to => 'custom_sites#security', :as => 'custom_sites_security'

  root :to => "home#index"
  get "about", to: 'home#about'

  # apipie
  namespace :api do
    namespace :v1 do
      resources :benefits do
        resources :sections
      end
      resources :site_configs
      devise_for :users, :controllers => { :sessions => "api/v1/sessions"}
    end
  end

end

app/views/shared/template1/_footer.html.haml
%footer
  .row.test.ft-widget-wrap
    %article#text-3.large-3.columns.widget.widget_text
      .textwidget
        %p
          \&#169;2014 Sisk. All Rights Reserved.
          %br/
          Site designed with love by
          %a{href: "http://www.theinfiniteagency.com"} Infinite
    %article#text-2.large-3.columns.widget.widget_text
      %h3 Member Benefits
      .textwidget
        %p
          %strong provided by The Sisk Company
          %br/
          4055 International Plaza
          %br/
          Suite 440
          %br/
          Fort Worth, TX 76109
    %article#text-4.large-3.columns.widget.widget_text
      .textwidget
        %p
          Toll Free: 1-800-899-7175
          %br/
          Local: 817-735-4884
          %br/
          %a{href: "mailto:info@siskcompany.com"} info@siskcompany.com
    %article#text-5.large-3.columns.widget.widget_text
      %h3 Sitemap
      %ul.sitemap
        %li
          %a{href: "/mb/#{@custom_site.url}"} Home
        %li
          = link_to "About", custom_sites_about_path(@custom_site.url)
%a.exit-off-canvas

app/views/shared/template1/_header.html.haml
%nav.tab-bar.show-for-medium-down
  %section.right-small
    %a.right-off-canvas-toggle.menu-icon
      %span
  %section.middle.tab-bar-section
    %a{href: "/mb/#{@custom_site.url}"}
      %img{src: "#{@logo}"}
%aside.right-off-canvas-menu
  = render 'shared/mobile_navigation_links'

.header
  .top-bar-container.contain-to-grid.show-for-large-up
    %nav.top-bar{"data-topbar" => ""}
      %ul.title-area
        %li.name
          %h1
            %a{href: "/mb/#{@custom_site.url}"}
              %img{src: "#{@logo}"}
      %section.top-bar-section
        %ul#main-menu.top-bar-menu.right
          = render 'shared/template_navigation_links'

app/views/shared/template1/_home_hero.html.haml
%section.container{role: "document"}
  .row
    %section#home-hero
      .row
        .large-7.columns.right
          .large-9.hide-for-medium-down
            %h2 Sample Text Goes Here
          .show-for-medium-down.center
            %h2 Sample Text Goes Here
        %aside.large-4.large-offset-1.home-login-form.left
          .inner
            #errorMSG
            = render 'shared/login_form'